#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Data-Integer
Version  : 0.006
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Data-Integer-0.006.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Data-Integer-0.006.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdata-integer-perl/libdata-integer-perl_0.006-1.debian.tar.xz
Summary  : 'details of the native integer data type'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Data-Integer-man
BuildRequires : perl(Module::Build)

%description
NAME
Data::Integer - details of the native integer data type
DESCRIPTION
This module is about the native integer numerical data type.  A native
integer is one of the types of datum that can appear in the numeric part
of a Perl scalar.  This module supplies constants describing the native
integer type.

%package man
Summary: man components for the perl-Data-Integer package.
Group: Default

%description man
man components for the perl-Data-Integer package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Data-Integer-0.006
mkdir -p %{_topdir}/BUILD/Data-Integer-0.006/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Data-Integer-0.006/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Data/Integer.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Data::Integer.3
